DROP TABLE IF EXISTS students cascade;

create table public.students
(
    id               bigint generated by default as identity
        constraint students_pk
            primary key,
    name             varchar not null,
    student_class_id bigint not null
);