DROP TABLE IF EXISTS users;

create table public.users
(
    id       integer generated by default as identity,
    name     varchar not null,
    password varchar not null,
    email    varchar not null,
    phone    varchar not null,
    role     varchar not null,
    constraint users_pk
        primary key (id)
);