DROP TABLE IF EXISTS lessons;


create table public.lessons
(
    id               integer generated by default as identity
        constraint lessons_pk
            primary key,
    lesson_time      timestamp not null,
    user_id          integer
        constraint lessons_users_id_fk
            references public.users
            on update cascade,
    student_class_id integer
        constraint lessons_student_classes_id_fk
            references public.student_classes
            on update cascade,
    predmet_id       integer
        constraint lessons_predmets_id_fk
            references public.predmets
            on update cascade,
    homework_id      integer
        constraint lessons_homeworks_id_fk
            references public.homeworks
            on update cascade
);