create table public.students
(
    id               integer generated by default as identity
        constraint students_pk
            primary key,
    name             varchar not null,
    student_class_id integer not null
);