create table public.lessons
(
    id               integer generated by default as identity
        constraint lessons_pk
            primary key,
    lesson_time      timestamp not null,
    user_id          integer   not null
        constraint lessons_users_id_fk
            references public.users,
    student_class_id integer   not null
        constraint lessons_student_classes_id_fk
            references public.student_classes,
    predmet_id       integer   not null
        constraint lessons_predmets_id_fk
            references public.predmets,
    homework_id      integer
        constraint lessons_homeworks_id_fk
            references public.homeworks
);